name: Backend Tests
on: 
  pull_request:

jobs: 

  check_paths:
    runs-on: ubuntu-latest
    outputs:
      should_run: ${{ steps.filter.outputs.backend }}
    steps: 
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3.0.2
        id: filter
        with:
          filters: |
            backend:
              - 'src/backend/**'
              - '.github/workflows/backend-tests.yaml'
  test:
    name: BackendScan
    needs: check_paths
    if: ${{ needs.check_paths.outputs.should_run == 'true' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install UV
        uses: astral-sh/setup-uv@v5

      - name: Setup Python
        run: uv python install

      - name: Install dependencies
        run: |
          uv sync --locked --dev

      - name: Linting wiht Ruff
        run: |
          uv run ruff check --output-format=github --target-version=py313 src tests
          uv run ruff format --diff --check --target-version=py313 src tests

      - name: Run tests with coverage
        run: |
          uv run pytest tests/ -v --cov=src/backend --cov-report=xml --cov-fail-under=80

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: ./src/backend/coverage.xml
          retention-days: 7
        if: ${{ always() }}

      - name: Coverage Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: ./src/backend/coverage.xml
          badge: true
          format: markdown
          output: both

      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          header: test-coverage
          recreate: true
          path: code-coverage-results.md

      - name: Run Backend Tests
        run: |
          uv run pytest

      - name: Build Docker Image
        run: docker build -t backend-app:latest .

      - name: Run Trivy Vulnerability Scanner
        uses: aquasecurity/trivy-action@0.30.0
        with: 
          image-ref: "backend-app:latest"
          format: "table"
          exit-code: "0"
          ignore-unfixed: true
          vuln-type: "os,library"
          severity: "CRITICAL,HIGH"

  trigger_e2e:
    name: Trigger E2E Tests
    needs: test
    if: success()
    uses: ./.github/workflows/e2e-tests.yaml

  trigger_gitops:
    name: Trigger GitOps
    needs: [build-and-push-backend, build-and-push-frontend]
    # Run if either build job succeeded (the other one will be skipped based on the tag)
    if: always() && (needs.build-and-push-backend.result == 'success' || needs.build-and-push-frontend.result == 'success')
    uses: ./.github/workflows/update-gitops.yaml
    with:
      tag: ${{ needs.build-and-push-backend.outputs.tags || needs.build-and-push-frontend.outputs.tags }}
      app: ${{ needs.build-and-push-backend.outputs.app || needs.build-and-push-frontend.outputs.app }}

    secrets:
      GITOPS_DEPLOY_KEY: ${{ secrets.GITOPS_DEPLOY_KEY }}
      DEVOPS_STUDY_APP: ${{ secrets.DEVOPS_STUDY_APP }}
